- name: Dotfiles Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /git
    - /git/wicksy

- name: Configfiles Git Repo
  git:
    repo: https://github.com/wicksy/configfiles.git
    dest: /git/wicksy/configfiles
    version: master
    clone: yes
    force: yes
    update: yes

- name: Links for root
  file:
    state: link
    src: /git/wicksy/configfiles/dotfiles/{{ item }}
    dest: /root/{{ item }}
    owner: root
    group: root
    mode: 0644
    force: yes
  with_items:
    - .bashrc
    - .vimrc

- name: Links for wicksy
  file:
    state: link
    src: /git/wicksy/configfiles/dotfiles/{{ item }}
    dest: /home/wicksy/{{ item }}
    owner: wicksy
    group: wicksy
    mode: 0644
    force: yes
  with_items:
    - .bashrc
    - .vimrc
