- name: Install vim plugins
  include: plugins.yml target={{ outer_item }}
  with_items:
    - /root/.vim
    - /home/wicksy/.vim
  loop_control:
    loop_var: outer_item

- name: Chown vim directories and files (wicksy)
  file:
    path: /home/wicksy/.vim
    state: directory
    owner: wicksy
    group: wicksy
    mode: 0755
    recurse: yes
