- name: Install Docker Key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Install Docker Repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    filename: /etc/apt/sources.list.d/docker
    state: present

- name: Install Docker Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - docker-engine

- name: Docker Service
  service:
    name: docker
    state: started
    enabled: yes
