- hosts: dell-inspiron
  remote_user: ansible
  become: true
  become_user: root
  become_method: sudo

  roles:
    - cron
    - core_pkg
    - core_pip
    - docker
    - dotfiles
    - entropy
    - git
    - mounts
    - ntp
    - ssh
    - sshkeys
    - timezone
    - vagrant
    - vim
    - users
